--
-- Script was generated by Devart dbForge Studio for MySQL, Version 2025.2.37.0
-- Product home page: https://www.devart.com/dbforge/mysql/studio
-- Script date 1/22/2026 11:37:07 PM
-- Server version: 8.0.44
--

--
-- Disable foreign keys
--
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

--
-- Set SQL mode
--
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

--
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE restaurant_mgmt;

--
-- Drop table `inventory_transaction`
--
DROP TABLE IF EXISTS inventory_transaction;

--
-- Drop table `purchase_item`
--
DROP TABLE IF EXISTS purchase_item;

--
-- Drop table `ingredient`
--
DROP TABLE IF EXISTS ingredient;

--
-- Drop table `purchase`
--
DROP TABLE IF EXISTS purchase;

--
-- Drop table `supplier`
--
DROP TABLE IF EXISTS supplier;

--
-- Drop table `role_permission`
--
DROP TABLE IF EXISTS role_permission;

--
-- Drop table `permission`
--
DROP TABLE IF EXISTS permission;

--
-- Drop table `service_error`
--
DROP TABLE IF EXISTS service_error;

--
-- Drop table `service_error_category`
--
DROP TABLE IF EXISTS service_error_category;

--
-- Drop table `payment`
--
DROP TABLE IF EXISTS payment;

--
-- Drop table `invoice`
--
DROP TABLE IF EXISTS invoice;

--
-- Drop table `reservation_table`
--
DROP TABLE IF EXISTS reservation_table;

--
-- Drop table `reservation`
--
DROP TABLE IF EXISTS reservation;

--
-- Drop table `customer`
--
DROP TABLE IF EXISTS customer;

--
-- Drop table `audit_log`
--
DROP TABLE IF EXISTS audit_log;

--
-- Drop table `auth_session`
--
DROP TABLE IF EXISTS auth_session;

--
-- Drop table `order_item`
--
DROP TABLE IF EXISTS order_item;

--
-- Drop table `orders`
--
DROP TABLE IF EXISTS orders;

--
-- Drop table `account`
--
DROP TABLE IF EXISTS account;

--
-- Drop table `role`
--
DROP TABLE IF EXISTS role;

--
-- Drop table `dish_media`
--
DROP TABLE IF EXISTS dish_media;

--
-- Drop table `dish`
--
DROP TABLE IF EXISTS dish;

--
-- Drop table `dish_category`
--
DROP TABLE IF EXISTS dish_category;

--
-- Drop table `table_media`
--
DROP TABLE IF EXISTS table_media;

--
-- Drop table `media_asset`
--
DROP TABLE IF EXISTS media_asset;

--
-- Drop table `restaurant_table`
--
DROP TABLE IF EXISTS restaurant_table;

--
-- Drop table `setting_item`
--
DROP TABLE IF EXISTS setting_item;

--
-- Drop table `setting_category`
--
DROP TABLE IF EXISTS setting_category;

--
-- Set default database
--
USE restaurant_mgmt;

--
-- Create table `setting_category`
--
CREATE TABLE setting_category (
  category_id bigint NOT NULL AUTO_INCREMENT,
  category_code varchar(50) NOT NULL,
  category_name varchar(100) NOT NULL,
  description varchar(255) DEFAULT NULL,
  PRIMARY KEY (category_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 2,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create index `category_code` on table `setting_category`
--
ALTER TABLE setting_category
ADD UNIQUE INDEX category_code (category_code);

--
-- Create table `setting_item`
--
CREATE TABLE setting_item (
  setting_id bigint NOT NULL AUTO_INCREMENT,
  category_id bigint NOT NULL,
  setting_code varchar(50) NOT NULL,
  setting_name varchar(100) NOT NULL,
  sort_order int DEFAULT 0,
  is_active tinyint(1) DEFAULT 1,
  PRIMARY KEY (setting_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 3,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create index `idx_setting_category` on table `setting_item`
--
ALTER TABLE setting_item
ADD INDEX idx_setting_category (category_id, is_active);

--
-- Create index `uq_setting` on table `setting_item`
--
ALTER TABLE setting_item
ADD UNIQUE INDEX uq_setting (category_id, setting_code);

--
-- Create foreign key
--
ALTER TABLE setting_item
ADD CONSTRAINT fk_setting_category FOREIGN KEY (category_id)
REFERENCES setting_category (category_id);

--
-- Create table `restaurant_table`
--
CREATE TABLE restaurant_table (
  table_id bigint NOT NULL AUTO_INCREMENT,
  table_code varchar(50) NOT NULL,
  capacity int NOT NULL,
  status_id bigint NOT NULL,
  PRIMARY KEY (table_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create index `table_code` on table `restaurant_table`
--
ALTER TABLE restaurant_table
ADD UNIQUE INDEX table_code (table_code);

--
-- Create foreign key
--
ALTER TABLE restaurant_table
ADD CONSTRAINT restaurant_table_ibfk_1 FOREIGN KEY (status_id)
REFERENCES setting_item (setting_id);

--
-- Create table `media_asset`
--
CREATE TABLE media_asset (
  media_id bigint NOT NULL AUTO_INCREMENT,
  media_type_id bigint NOT NULL,
  url varchar(500) NOT NULL,
  mime_type varchar(100) DEFAULT NULL,
  width int DEFAULT NULL,
  height int DEFAULT NULL,
  duration_sec int DEFAULT NULL,
  created_at datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (media_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create foreign key
--
ALTER TABLE media_asset
ADD CONSTRAINT media_asset_ibfk_1 FOREIGN KEY (media_type_id)
REFERENCES setting_item (setting_id);

--
-- Create table `table_media`
--
CREATE TABLE table_media (
  table_id bigint NOT NULL,
  media_id bigint NOT NULL,
  is_primary tinyint(1) DEFAULT 0,
  PRIMARY KEY (table_id, media_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create foreign key
--
ALTER TABLE table_media
ADD CONSTRAINT table_media_ibfk_1 FOREIGN KEY (table_id)
REFERENCES restaurant_table (table_id);

--
-- Create foreign key
--
ALTER TABLE table_media
ADD CONSTRAINT table_media_ibfk_2 FOREIGN KEY (media_id)
REFERENCES media_asset (media_id);

--
-- Create table `dish_category`
--
CREATE TABLE dish_category (
  category_id bigint NOT NULL AUTO_INCREMENT,
  category_name varchar(100) NOT NULL,
  PRIMARY KEY (category_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create table `dish`
--
CREATE TABLE dish (
  dish_id bigint NOT NULL AUTO_INCREMENT,
  category_id bigint NOT NULL,
  dish_name varchar(200) NOT NULL,
  price decimal(12, 2) NOT NULL,
  status_id bigint NOT NULL,
  created_at datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (dish_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create index `idx_dish_status` on table `dish`
--
ALTER TABLE dish
ADD INDEX idx_dish_status (status_id);

--
-- Create foreign key
--
ALTER TABLE dish
ADD CONSTRAINT dish_ibfk_1 FOREIGN KEY (category_id)
REFERENCES dish_category (category_id);

--
-- Create foreign key
--
ALTER TABLE dish
ADD CONSTRAINT dish_ibfk_2 FOREIGN KEY (status_id)
REFERENCES setting_item (setting_id);

--
-- Create table `dish_media`
--
CREATE TABLE dish_media (
  dish_id bigint NOT NULL,
  media_id bigint NOT NULL,
  is_primary tinyint(1) DEFAULT 0,
  PRIMARY KEY (dish_id, media_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create foreign key
--
ALTER TABLE dish_media
ADD CONSTRAINT dish_media_ibfk_1 FOREIGN KEY (dish_id)
REFERENCES dish (dish_id);

--
-- Create foreign key
--
ALTER TABLE dish_media
ADD CONSTRAINT dish_media_ibfk_2 FOREIGN KEY (media_id)
REFERENCES media_asset (media_id);

--
-- Create table `role`
--
CREATE TABLE role (
  role_id bigint NOT NULL AUTO_INCREMENT,
  role_code varchar(50) NOT NULL,
  role_name varchar(100) NOT NULL,
  PRIMARY KEY (role_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 3,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create index `role_code` on table `role`
--
ALTER TABLE role
ADD UNIQUE INDEX role_code (role_code);

--
-- Create table `account`
--
CREATE TABLE account (
  account_id bigint NOT NULL AUTO_INCREMENT,
  full_name varchar(150) NOT NULL,
  phone varchar(30) DEFAULT NULL,
  email varchar(150) DEFAULT NULL,
  role_id bigint NOT NULL,
  status_id bigint NOT NULL,
  created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  username varchar(100) NOT NULL,
  password_hash varchar(255) NOT NULL,
  is_locked tinyint(1) NOT NULL DEFAULT 0,
  last_login_at datetime DEFAULT NULL,
  PRIMARY KEY (account_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 3,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create index `email` on table `account`
--
ALTER TABLE account
ADD UNIQUE INDEX email (email);

--
-- Create index `username` on table `account`
--
ALTER TABLE account
ADD UNIQUE INDEX username (username);

--
-- Create foreign key
--
ALTER TABLE account
ADD CONSTRAINT account_ibfk_1 FOREIGN KEY (role_id)
REFERENCES role (role_id);

--
-- Create foreign key
--
ALTER TABLE account
ADD CONSTRAINT account_ibfk_2 FOREIGN KEY (status_id)
REFERENCES setting_item (setting_id);

--
-- Create table `orders`
--
CREATE TABLE orders (
  order_id bigint NOT NULL AUTO_INCREMENT,
  table_id bigint NOT NULL,
  staff_id bigint NOT NULL,
  source_id bigint NOT NULL,
  status_id bigint NOT NULL,
  created_at datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (order_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create index `idx_order_status` on table `orders`
--
ALTER TABLE orders
ADD INDEX idx_order_status (status_id, created_at);

--
-- Create foreign key
--
ALTER TABLE orders
ADD CONSTRAINT orders_ibfk_1 FOREIGN KEY (table_id)
REFERENCES restaurant_table (table_id);

--
-- Create foreign key
--
ALTER TABLE orders
ADD CONSTRAINT orders_ibfk_2 FOREIGN KEY (staff_id)
REFERENCES account (account_id);

--
-- Create foreign key
--
ALTER TABLE orders
ADD CONSTRAINT orders_ibfk_3 FOREIGN KEY (source_id)
REFERENCES setting_item (setting_id);

--
-- Create foreign key
--
ALTER TABLE orders
ADD CONSTRAINT orders_ibfk_4 FOREIGN KEY (status_id)
REFERENCES setting_item (setting_id);

--
-- Create table `order_item`
--
CREATE TABLE order_item (
  order_item_id bigint NOT NULL AUTO_INCREMENT,
  order_id bigint NOT NULL,
  dish_id bigint NOT NULL,
  quantity int NOT NULL,
  price decimal(12, 2) NOT NULL,
  status_id bigint NOT NULL,
  reject_reason varchar(255) DEFAULT NULL,
  PRIMARY KEY (order_item_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create index `idx_order_item_status` on table `order_item`
--
ALTER TABLE order_item
ADD INDEX idx_order_item_status (status_id);

--
-- Create foreign key
--
ALTER TABLE order_item
ADD CONSTRAINT order_item_ibfk_1 FOREIGN KEY (order_id)
REFERENCES orders (order_id);

--
-- Create foreign key
--
ALTER TABLE order_item
ADD CONSTRAINT order_item_ibfk_2 FOREIGN KEY (dish_id)
REFERENCES dish (dish_id);

--
-- Create foreign key
--
ALTER TABLE order_item
ADD CONSTRAINT order_item_ibfk_3 FOREIGN KEY (status_id)
REFERENCES setting_item (setting_id);

--
-- Create table `auth_session`
--
CREATE TABLE auth_session (
  session_id bigint NOT NULL AUTO_INCREMENT,
  user_id bigint NOT NULL,
  token_hash varchar(255) NOT NULL,
  expires_at datetime NOT NULL,
  created_at datetime DEFAULT CURRENT_TIMESTAMP,
  revoked tinyint(1) DEFAULT 0,
  device_info varchar(500) DEFAULT NULL,
  ip_address varchar(45) DEFAULT NULL,
  PRIMARY KEY (session_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 2,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create index `idx_session_user` on table `auth_session`
--
ALTER TABLE auth_session
ADD INDEX idx_session_user (user_id, expires_at);

--
-- Create foreign key
--
ALTER TABLE auth_session
ADD CONSTRAINT auth_session_ibfk_1 FOREIGN KEY (user_id)
REFERENCES account (account_id);

--
-- Create table `audit_log`
--
CREATE TABLE audit_log (
  log_id bigint NOT NULL AUTO_INCREMENT,
  staff_id bigint DEFAULT NULL,
  action_code varchar(100) DEFAULT NULL,
  target_table varchar(100) DEFAULT NULL,
  target_id bigint DEFAULT NULL,
  created_at datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (log_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create index `idx_audit_time` on table `audit_log`
--
ALTER TABLE audit_log
ADD INDEX idx_audit_time (created_at);

--
-- Create foreign key
--
ALTER TABLE audit_log
ADD CONSTRAINT audit_log_ibfk_1 FOREIGN KEY (staff_id)
REFERENCES account (account_id);

--
-- Create table `customer`
--
CREATE TABLE customer (
  customer_id bigint NOT NULL AUTO_INCREMENT,
  full_name varchar(150) DEFAULT NULL,
  phone varchar(30) NOT NULL,
  email varchar(150) DEFAULT NULL,
  is_member tinyint(1) DEFAULT 0,
  loyalty_points int DEFAULT 0,
  created_at datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (customer_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create index `phone` on table `customer`
--
ALTER TABLE customer
ADD UNIQUE INDEX phone (phone);

--
-- Create table `reservation`
--
CREATE TABLE reservation (
  reservation_id bigint NOT NULL AUTO_INCREMENT,
  customer_id bigint DEFAULT NULL,
  customer_name varchar(150) NOT NULL,
  phone varchar(30) NOT NULL,
  email varchar(150) DEFAULT NULL,
  party_size int NOT NULL,
  reserved_time datetime NOT NULL,
  source_id bigint NOT NULL,
  status_id bigint NOT NULL,
  created_at datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (reservation_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create index `idx_reservation_time` on table `reservation`
--
ALTER TABLE reservation
ADD INDEX idx_reservation_time (reserved_time, status_id);

--
-- Create foreign key
--
ALTER TABLE reservation
ADD CONSTRAINT reservation_ibfk_1 FOREIGN KEY (customer_id)
REFERENCES customer (customer_id);

--
-- Create foreign key
--
ALTER TABLE reservation
ADD CONSTRAINT reservation_ibfk_2 FOREIGN KEY (source_id)
REFERENCES setting_item (setting_id);

--
-- Create foreign key
--
ALTER TABLE reservation
ADD CONSTRAINT reservation_ibfk_3 FOREIGN KEY (status_id)
REFERENCES setting_item (setting_id);

--
-- Create table `reservation_table`
--
CREATE TABLE reservation_table (
  reservation_id bigint NOT NULL,
  table_id bigint NOT NULL,
  PRIMARY KEY (reservation_id, table_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create foreign key
--
ALTER TABLE reservation_table
ADD CONSTRAINT reservation_table_ibfk_1 FOREIGN KEY (reservation_id)
REFERENCES reservation (reservation_id);

--
-- Create foreign key
--
ALTER TABLE reservation_table
ADD CONSTRAINT reservation_table_ibfk_2 FOREIGN KEY (table_id)
REFERENCES restaurant_table (table_id);

--
-- Create table `invoice`
--
CREATE TABLE invoice (
  invoice_id bigint NOT NULL AUTO_INCREMENT,
  order_id bigint NOT NULL,
  staff_id bigint NOT NULL,
  customer_id bigint DEFAULT NULL,
  status_id bigint NOT NULL,
  total_amount decimal(14, 2) NOT NULL,
  tip_amount decimal(12, 2) DEFAULT 0.00,
  created_at datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (invoice_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create index `idx_invoice_status` on table `invoice`
--
ALTER TABLE invoice
ADD INDEX idx_invoice_status (status_id, created_at);

--
-- Create index `order_id` on table `invoice`
--
ALTER TABLE invoice
ADD UNIQUE INDEX order_id (order_id);

--
-- Create foreign key
--
ALTER TABLE invoice
ADD CONSTRAINT invoice_ibfk_1 FOREIGN KEY (order_id)
REFERENCES orders (order_id);

--
-- Create foreign key
--
ALTER TABLE invoice
ADD CONSTRAINT invoice_ibfk_2 FOREIGN KEY (staff_id)
REFERENCES account (account_id);

--
-- Create foreign key
--
ALTER TABLE invoice
ADD CONSTRAINT invoice_ibfk_3 FOREIGN KEY (customer_id)
REFERENCES customer (customer_id);

--
-- Create foreign key
--
ALTER TABLE invoice
ADD CONSTRAINT invoice_ibfk_4 FOREIGN KEY (status_id)
REFERENCES setting_item (setting_id);

--
-- Create table `payment`
--
CREATE TABLE payment (
  payment_id bigint NOT NULL AUTO_INCREMENT,
  invoice_id bigint NOT NULL,
  method_id bigint NOT NULL,
  received_amount decimal(14, 2) NOT NULL,
  change_amount decimal(14, 2) NOT NULL,
  paid_at datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (payment_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create foreign key
--
ALTER TABLE payment
ADD CONSTRAINT payment_ibfk_1 FOREIGN KEY (invoice_id)
REFERENCES invoice (invoice_id);

--
-- Create foreign key
--
ALTER TABLE payment
ADD CONSTRAINT payment_ibfk_2 FOREIGN KEY (method_id)
REFERENCES setting_item (setting_id);

--
-- Create table `service_error_category`
--
CREATE TABLE service_error_category (
  category_id bigint NOT NULL AUTO_INCREMENT,
  category_code varchar(50) NOT NULL,
  category_name varchar(150) NOT NULL,
  description varchar(255) DEFAULT NULL,
  PRIMARY KEY (category_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create index `category_code` on table `service_error_category`
--
ALTER TABLE service_error_category
ADD UNIQUE INDEX category_code (category_code);

--
-- Create table `service_error`
--
CREATE TABLE service_error (
  error_id bigint NOT NULL AUTO_INCREMENT,
  staff_id bigint NOT NULL,
  order_id bigint DEFAULT NULL,
  order_item_id bigint DEFAULT NULL,
  table_id bigint DEFAULT NULL,
  category_id bigint NOT NULL,
  severity_id bigint NOT NULL,
  description varchar(500) NOT NULL,
  penalty_amount decimal(12, 2) DEFAULT 0.00,
  is_resolved tinyint(1) DEFAULT 0,
  resolved_by bigint DEFAULT NULL,
  resolved_at datetime DEFAULT NULL,
  created_at datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (error_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create index `idx_service_error_order` on table `service_error`
--
ALTER TABLE service_error
ADD INDEX idx_service_error_order (order_id);

--
-- Create index `idx_service_error_staff` on table `service_error`
--
ALTER TABLE service_error
ADD INDEX idx_service_error_staff (staff_id, created_at);

--
-- Create foreign key
--
ALTER TABLE service_error
ADD CONSTRAINT service_error_ibfk_1 FOREIGN KEY (staff_id)
REFERENCES account (account_id);

--
-- Create foreign key
--
ALTER TABLE service_error
ADD CONSTRAINT service_error_ibfk_2 FOREIGN KEY (order_id)
REFERENCES orders (order_id);

--
-- Create foreign key
--
ALTER TABLE service_error
ADD CONSTRAINT service_error_ibfk_3 FOREIGN KEY (order_item_id)
REFERENCES order_item (order_item_id);

--
-- Create foreign key
--
ALTER TABLE service_error
ADD CONSTRAINT service_error_ibfk_4 FOREIGN KEY (table_id)
REFERENCES restaurant_table (table_id);

--
-- Create foreign key
--
ALTER TABLE service_error
ADD CONSTRAINT service_error_ibfk_5 FOREIGN KEY (category_id)
REFERENCES service_error_category (category_id);

--
-- Create foreign key
--
ALTER TABLE service_error
ADD CONSTRAINT service_error_ibfk_6 FOREIGN KEY (severity_id)
REFERENCES setting_item (setting_id);

--
-- Create foreign key
--
ALTER TABLE service_error
ADD CONSTRAINT service_error_ibfk_7 FOREIGN KEY (resolved_by)
REFERENCES account (account_id);

--
-- Create table `permission`
--
CREATE TABLE permission (
  permission_id bigint NOT NULL AUTO_INCREMENT,
  screen_code varchar(100) NOT NULL,
  action_code varchar(20) NOT NULL,
  PRIMARY KEY (permission_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 5,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create table `role_permission`
--
CREATE TABLE role_permission (
  role_id bigint NOT NULL,
  permission_id bigint NOT NULL,
  PRIMARY KEY (role_id, permission_id)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 4096,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create foreign key
--
ALTER TABLE role_permission
ADD CONSTRAINT role_permission_ibfk_1 FOREIGN KEY (role_id)
REFERENCES role (role_id);

--
-- Create foreign key
--
ALTER TABLE role_permission
ADD CONSTRAINT role_permission_ibfk_2 FOREIGN KEY (permission_id)
REFERENCES permission (permission_id);

--
-- Create table `supplier`
--
CREATE TABLE supplier (
  supplier_id bigint NOT NULL AUTO_INCREMENT,
  supplier_name varchar(200) NOT NULL,
  phone varchar(50) DEFAULT NULL,
  email varchar(150) DEFAULT NULL,
  PRIMARY KEY (supplier_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create table `purchase`
--
CREATE TABLE purchase (
  purchase_id bigint NOT NULL AUTO_INCREMENT,
  supplier_id bigint NOT NULL,
  staff_id bigint NOT NULL,
  total_amount decimal(14, 2) DEFAULT NULL,
  purchased_at datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (purchase_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create foreign key
--
ALTER TABLE purchase
ADD CONSTRAINT purchase_ibfk_1 FOREIGN KEY (supplier_id)
REFERENCES supplier (supplier_id);

--
-- Create foreign key
--
ALTER TABLE purchase
ADD CONSTRAINT purchase_ibfk_2 FOREIGN KEY (staff_id)
REFERENCES account (account_id);

--
-- Create table `ingredient`
--
CREATE TABLE ingredient (
  ingredient_id bigint NOT NULL AUTO_INCREMENT,
  ingredient_name varchar(200) NOT NULL,
  unit varchar(20) NOT NULL,
  PRIMARY KEY (ingredient_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create table `purchase_item`
--
CREATE TABLE purchase_item (
  purchase_item_id bigint NOT NULL AUTO_INCREMENT,
  purchase_id bigint NOT NULL,
  ingredient_id bigint NOT NULL,
  quantity decimal(12, 2) NOT NULL,
  unit_price decimal(12, 2) DEFAULT NULL,
  PRIMARY KEY (purchase_item_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create foreign key
--
ALTER TABLE purchase_item
ADD CONSTRAINT purchase_item_ibfk_1 FOREIGN KEY (purchase_id)
REFERENCES purchase (purchase_id);

--
-- Create foreign key
--
ALTER TABLE purchase_item
ADD CONSTRAINT purchase_item_ibfk_2 FOREIGN KEY (ingredient_id)
REFERENCES ingredient (ingredient_id);

--
-- Create table `inventory_transaction`
--
CREATE TABLE inventory_transaction (
  transaction_id bigint NOT NULL AUTO_INCREMENT,
  ingredient_id bigint NOT NULL,
  purchase_id bigint DEFAULT NULL,
  supplier_id bigint DEFAULT NULL,
  quantity decimal(12, 2) NOT NULL,
  type_id bigint NOT NULL,
  created_at datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (transaction_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create index `idx_inventory_type` on table `inventory_transaction`
--
ALTER TABLE inventory_transaction
ADD INDEX idx_inventory_type (type_id, created_at);

--
-- Create foreign key
--
ALTER TABLE inventory_transaction
ADD CONSTRAINT inventory_transaction_ibfk_1 FOREIGN KEY (ingredient_id)
REFERENCES ingredient (ingredient_id);

--
-- Create foreign key
--
ALTER TABLE inventory_transaction
ADD CONSTRAINT inventory_transaction_ibfk_2 FOREIGN KEY (purchase_id)
REFERENCES purchase (purchase_id);

--
-- Create foreign key
--
ALTER TABLE inventory_transaction
ADD CONSTRAINT inventory_transaction_ibfk_3 FOREIGN KEY (supplier_id)
REFERENCES supplier (supplier_id);

--
-- Create foreign key
--
ALTER TABLE inventory_transaction
ADD CONSTRAINT inventory_transaction_ibfk_4 FOREIGN KEY (type_id)
REFERENCES setting_item (setting_id);

-- 
-- Dumping data for table setting_category
--
INSERT INTO setting_category(category_id, category_code, category_name, description) VALUES
(1, 'account_status', 'Account Status', 'This is setting type of account status');

-- 
-- Dumping data for table setting_item
--
INSERT INTO setting_item(setting_id, category_id, setting_code, setting_name, sort_order, is_active) VALUES
(1, 1, 'account_active', 'Active', 1, 1),
(2, 1, 'account_inactive', 'Inactive', 1, 1);

-- Table restaurant_mgmt.dish_category does not contain any data (it is empty)

-- 
-- Dumping data for table role
--
INSERT INTO role(role_id, role_code, role_name) VALUES
(1, 'ADMIN', 'Admin'),
(2, 'STAFF', 'Staff');

-- Table restaurant_mgmt.restaurant_table does not contain any data (it is empty)

-- Table restaurant_mgmt.dish does not contain any data (it is empty)

-- Table restaurant_mgmt.customer does not contain any data (it is empty)

-- 
-- Dumping data for table account
--
INSERT INTO account(account_id, full_name, phone, email, role_id, status_id, created_at, username, password_hash, is_locked, last_login_at) VALUES
(1, 'dat', '0342164017', 'nguyenducdat0406@gmail.com', 2, 1, '2026-01-22 23:16:23', 'staff_test_acc', '$2a$12$Vs18zSfPhFdp2l74aOoCzuaiKhaDNg1xc7LVlErF/NoGLxo2ctwYm', 0, NULL),
(2, 'admin', '0999999999', 'admin@gmail.com', 1, 1, '2026-01-22 23:19:05', 'admin', '$2a$12$PGj7asKjGxknX3QWEO9YV.sR/jI4gDXgv2e/NSz/yhY6fmfsZoi4q', 0, '2026-01-22 16:32:57');

-- Table restaurant_mgmt.service_error_category does not contain any data (it is empty)

-- Table restaurant_mgmt.orders does not contain any data (it is empty)

-- Table restaurant_mgmt.order_item does not contain any data (it is empty)

-- 
-- Dumping data for table permission
--
INSERT INTO permission(permission_id, screen_code, action_code) VALUES
(1, 'ACCOUNT', 'CREATE'),
(2, 'ACCOUNT', 'UPDATE'),
(3, 'ACCOUNT', 'DELETE'),
(4, 'ACCOUNT', 'READ');

-- Table restaurant_mgmt.reservation does not contain any data (it is empty)

-- Table restaurant_mgmt.invoice does not contain any data (it is empty)

-- Table restaurant_mgmt.supplier does not contain any data (it is empty)

-- Table restaurant_mgmt.purchase does not contain any data (it is empty)

-- Table restaurant_mgmt.ingredient does not contain any data (it is empty)

-- Table restaurant_mgmt.media_asset does not contain any data (it is empty)

-- Table restaurant_mgmt.table_media does not contain any data (it is empty)

-- Table restaurant_mgmt.service_error does not contain any data (it is empty)

-- 
-- Dumping data for table role_permission
--
INSERT INTO role_permission(role_id, permission_id) VALUES
(1, 1),
(1, 2),
(1, 3),
(1, 4);

-- Table restaurant_mgmt.reservation_table does not contain any data (it is empty)

-- Table restaurant_mgmt.purchase_item does not contain any data (it is empty)

-- Table restaurant_mgmt.payment does not contain any data (it is empty)

-- Table restaurant_mgmt.inventory_transaction does not contain any data (it is empty)

-- Table restaurant_mgmt.dish_media does not contain any data (it is empty)

-- 
-- Dumping data for table auth_session
--
INSERT INTO auth_session(session_id, user_id, token_hash, expires_at, created_at, revoked, device_info, ip_address) VALUES
(1, 2, '+4ZiJILZ0OEypxAyrrNok8zXdsnSutADmosGItP4gLo=', '2026-01-29 16:32:18', '2026-01-22 16:32:19', 0, 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/144.0.0.0 Safari/537.36', '::1');

-- Table restaurant_mgmt.audit_log does not contain any data (it is empty)

--
-- Restore previous SQL mode
--
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

--
-- Enable foreign keys
--
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;