--
-- Script was generated by Devart dbForge Studio for MySQL, Version 2025.2.37.0
-- Product home page: https://www.devart.com/dbforge/mysql/studio
-- Script date 1/27/2026 10:10:47 PM
-- Server version: 8.0.44
--

--
-- Disable foreign keys
--
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

--
-- Set SQL mode
--
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

--
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE restaurant_mgmt;

--
-- Drop table `order_promotion`
--
DROP TABLE IF EXISTS order_promotion;

--
-- Drop table `promotion_rule`
--
DROP TABLE IF EXISTS promotion_rule;

--
-- Drop table `promotion_target`
--
DROP TABLE IF EXISTS promotion_target;

--
-- Drop table `promotion`
--
DROP TABLE IF EXISTS promotion;

--
-- Drop table `role_permission`
--
DROP TABLE IF EXISTS role_permission;

--
-- Drop table `permission`
--
DROP TABLE IF EXISTS permission;

--
-- Drop table `service_error`
--
DROP TABLE IF EXISTS service_error;

--
-- Drop table `service_error_category`
--
DROP TABLE IF EXISTS service_error_category;

--
-- Drop table `current_stock`
--
DROP TABLE IF EXISTS current_stock;

--
-- Drop table `inventory_transaction_item`
--
DROP TABLE IF EXISTS inventory_transaction_item;

--
-- Drop table `recipe`
--
DROP TABLE IF EXISTS recipe;

--
-- Drop table `ingredient`
--
DROP TABLE IF EXISTS ingredient;

--
-- Drop table `supplier`
--
DROP TABLE IF EXISTS supplier;

--
-- Drop table `dish_media`
--
DROP TABLE IF EXISTS dish_media;

--
-- Drop table `order_item`
--
DROP TABLE IF EXISTS order_item;

--
-- Drop table `dish`
--
DROP TABLE IF EXISTS dish;

--
-- Drop table `dish_category`
--
DROP TABLE IF EXISTS dish_category;

--
-- Drop table `payment`
--
DROP TABLE IF EXISTS payment;

--
-- Drop table `orders`
--
DROP TABLE IF EXISTS orders;

--
-- Drop table `reservation_table`
--
DROP TABLE IF EXISTS reservation_table;

--
-- Drop table `reservation`
--
DROP TABLE IF EXISTS reservation;

--
-- Drop table `customer`
--
DROP TABLE IF EXISTS customer;

--
-- Drop table `inventory_transaction_media`
--
DROP TABLE IF EXISTS inventory_transaction_media;

--
-- Drop table `table_media`
--
DROP TABLE IF EXISTS table_media;

--
-- Drop table `restaurant_table`
--
DROP TABLE IF EXISTS restaurant_table;

--
-- Drop table `media_asset`
--
DROP TABLE IF EXISTS media_asset;

--
-- Drop table `audit_log`
--
DROP TABLE IF EXISTS audit_log;

--
-- Drop table `auth_session`
--
DROP TABLE IF EXISTS auth_session;

--
-- Drop table `inventory_transaction`
--
DROP TABLE IF EXISTS inventory_transaction;

--
-- Drop table `staff_account`
--
DROP TABLE IF EXISTS staff_account;

--
-- Drop table `role`
--
DROP TABLE IF EXISTS role;

--
-- Set default database
--
USE restaurant_mgmt;

--
-- Create table `role`
--
CREATE TABLE role (
  role_id bigint NOT NULL AUTO_INCREMENT,
  role_code varchar(50) NOT NULL,
  role_name varchar(100) NOT NULL,
  PRIMARY KEY (role_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 3,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create index `role_code` on table `role`
--
ALTER TABLE role
ADD UNIQUE INDEX role_code (role_code);

--
-- Create table `staff_account`
--
CREATE TABLE staff_account (
  account_id bigint NOT NULL AUTO_INCREMENT,
  full_name varchar(150) NOT NULL,
  phone varchar(30) DEFAULT NULL,
  email varchar(150) DEFAULT NULL,
  role_id bigint NOT NULL,
  account_status tinyint UNSIGNED NOT NULL DEFAULT 1 COMMENT 'AccountStatus: 1=ACTIVE,2=INACTIVE,3=LOCKED',
  created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  username varchar(100) NOT NULL,
  password_hash varchar(255) NOT NULL,
  is_locked tinyint(1) NOT NULL DEFAULT 0,
  last_login_at datetime DEFAULT NULL,
  PRIMARY KEY (account_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 3,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create index `email` on table `staff_account`
--
ALTER TABLE staff_account
ADD UNIQUE INDEX email (email);

--
-- Create index `username` on table `staff_account`
--
ALTER TABLE staff_account
ADD UNIQUE INDEX username (username);

--
-- Create foreign key
--
ALTER TABLE staff_account
ADD CONSTRAINT staff_account_ibfk_1 FOREIGN KEY (role_id)
REFERENCES role (role_id);

--
-- Create table `inventory_transaction`
--
CREATE TABLE inventory_transaction (
  transaction_id bigint NOT NULL AUTO_INCREMENT,
  type tinyint NOT NULL COMMENT '1=IN, 2=OUT, 3=ADJUST',
  status tinyint NOT NULL COMMENT '1=DRAFT,2=PENDING_APPROVAL,3=COMPLETED,4=CANCELLED',
  created_by bigint DEFAULT NULL,
  created_at datetime DEFAULT CURRENT_TIMESTAMP,
  note varchar(255) DEFAULT NULL,
  PRIMARY KEY (transaction_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create index `idx_inventory_transaction_dir_time` on table `inventory_transaction`
--
ALTER TABLE inventory_transaction
ADD INDEX idx_inventory_transaction_dir_time (type, created_at);

--
-- Create index `idx_inventory_transaction_time` on table `inventory_transaction`
--
ALTER TABLE inventory_transaction
ADD INDEX idx_inventory_transaction_time (created_at);

--
-- Create foreign key
--
ALTER TABLE inventory_transaction
ADD CONSTRAINT fk_inventory_transaction_staff FOREIGN KEY (created_by)
REFERENCES staff_account (account_id);

--
-- Create table `auth_session`
--
CREATE TABLE auth_session (
  session_id bigint NOT NULL AUTO_INCREMENT,
  user_id bigint NOT NULL,
  token_hash varchar(255) NOT NULL,
  expires_at datetime NOT NULL,
  created_at datetime DEFAULT CURRENT_TIMESTAMP,
  revoked tinyint(1) DEFAULT 0,
  device_info varchar(500) DEFAULT NULL,
  ip_address varchar(45) DEFAULT NULL,
  PRIMARY KEY (session_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 3,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create index `idx_session_user` on table `auth_session`
--
ALTER TABLE auth_session
ADD INDEX idx_session_user (user_id, expires_at);

--
-- Create foreign key
--
ALTER TABLE auth_session
ADD CONSTRAINT auth_session_ibfk_1 FOREIGN KEY (user_id)
REFERENCES staff_account (account_id);

--
-- Create table `audit_log`
--
CREATE TABLE audit_log (
  log_id bigint NOT NULL AUTO_INCREMENT,
  staff_id bigint DEFAULT NULL,
  action_code varchar(100) DEFAULT NULL,
  target_table varchar(100) DEFAULT NULL,
  target_id bigint DEFAULT NULL,
  created_at datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (log_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create index `idx_audit_time` on table `audit_log`
--
ALTER TABLE audit_log
ADD INDEX idx_audit_time (created_at);

--
-- Create foreign key
--
ALTER TABLE audit_log
ADD CONSTRAINT audit_log_ibfk_1 FOREIGN KEY (staff_id)
REFERENCES staff_account (account_id);

--
-- Create table `media_asset`
--
CREATE TABLE media_asset (
  media_id bigint NOT NULL AUTO_INCREMENT,
  media_type_id tinyint UNSIGNED NOT NULL COMMENT 'MediaType (numeric enum in app)',
  url varchar(500) NOT NULL,
  mime_type varchar(100) DEFAULT NULL,
  width int DEFAULT NULL,
  height int DEFAULT NULL,
  duration_sec int DEFAULT NULL,
  created_at datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (media_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create index `media_type_id` on table `media_asset`
--
ALTER TABLE media_asset
ADD INDEX media_type_id (media_type_id);

--
-- Create table `restaurant_table`
--
CREATE TABLE restaurant_table (
  table_id bigint NOT NULL AUTO_INCREMENT,
  table_code varchar(50) NOT NULL,
  capacity int NOT NULL,
  table_status tinyint UNSIGNED NOT NULL DEFAULT 1 COMMENT 'TableStatus: 1=AVAILABLE,2=OCCUPIED,3=RESERVED,4=LOCKED',
  table_qr_img bigint DEFAULT NULL,
  table_type tinyint UNSIGNED NOT NULL COMMENT 'TableType (numeric enum in app)',
  PRIMARY KEY (table_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create index `FK_restaurant_table_table_type` on table `restaurant_table`
--
ALTER TABLE restaurant_table
ADD INDEX FK_restaurant_table_table_type (table_type);

--
-- Create index `table_code` on table `restaurant_table`
--
ALTER TABLE restaurant_table
ADD UNIQUE INDEX table_code (table_code);

--
-- Create foreign key
--
ALTER TABLE restaurant_table
ADD CONSTRAINT FK_restaurant_table_table_qr_img FOREIGN KEY (table_qr_img)
REFERENCES media_asset (media_id) ON DELETE CASCADE;

--
-- Create table `table_media`
--
CREATE TABLE table_media (
  table_id bigint NOT NULL,
  media_id bigint NOT NULL,
  is_primary tinyint(1) DEFAULT 0,
  PRIMARY KEY (table_id, media_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create foreign key
--
ALTER TABLE table_media
ADD CONSTRAINT table_media_ibfk_1 FOREIGN KEY (table_id)
REFERENCES restaurant_table (table_id);

--
-- Create foreign key
--
ALTER TABLE table_media
ADD CONSTRAINT table_media_ibfk_2 FOREIGN KEY (media_id)
REFERENCES media_asset (media_id);

--
-- Create table `inventory_transaction_media`
--
CREATE TABLE inventory_transaction_media (
  transaction_id bigint NOT NULL,
  media_id bigint NOT NULL,
  is_primary tinyint(1) DEFAULT 0,
  PRIMARY KEY (transaction_id, media_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create index `idx_inventory_transaction_media_media` on table `inventory_transaction_media`
--
ALTER TABLE inventory_transaction_media
ADD INDEX idx_inventory_transaction_media_media (media_id);

--
-- Create index `idx_inventory_transaction_media_primary` on table `inventory_transaction_media`
--
ALTER TABLE inventory_transaction_media
ADD INDEX idx_inventory_transaction_media_primary (transaction_id, is_primary);

--
-- Create foreign key
--
ALTER TABLE inventory_transaction_media
ADD CONSTRAINT fk_inventory_transaction_media_asset FOREIGN KEY (media_id)
REFERENCES media_asset (media_id) ON DELETE CASCADE;

--
-- Create foreign key
--
ALTER TABLE inventory_transaction_media
ADD CONSTRAINT fk_inventory_transaction_media_transaction FOREIGN KEY (transaction_id)
REFERENCES inventory_transaction (transaction_id) ON DELETE CASCADE;

--
-- Create table `customer`
--
CREATE TABLE customer (
  customer_id bigint NOT NULL AUTO_INCREMENT,
  full_name varchar(150) DEFAULT NULL,
  phone varchar(30) NOT NULL,
  email varchar(150) DEFAULT NULL,
  is_member tinyint(1) DEFAULT 0,
  loyalty_points int DEFAULT 0,
  created_at datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (customer_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create index `phone` on table `customer`
--
ALTER TABLE customer
ADD UNIQUE INDEX phone (phone);

--
-- Create table `reservation`
--
CREATE TABLE reservation (
  reservation_id bigint NOT NULL AUTO_INCREMENT,
  customer_id bigint DEFAULT NULL,
  customer_name varchar(150) NOT NULL,
  phone varchar(30) NOT NULL,
  email varchar(150) DEFAULT NULL,
  party_size int NOT NULL,
  reserved_time datetime NOT NULL,
  source_id tinyint UNSIGNED NOT NULL COMMENT 'ReservationSource (numeric enum in app)',
  reservation_status tinyint UNSIGNED NOT NULL DEFAULT 1 COMMENT 'ReservationStatus: 1=PENDING,2=CONFIRMED,3=CHECKED_IN,4=CANCELLED,5=NO_SHOW',
  created_at datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (reservation_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create index `idx_reservation_time` on table `reservation`
--
ALTER TABLE reservation
ADD INDEX idx_reservation_time (reserved_time);

--
-- Create index `source_id` on table `reservation`
--
ALTER TABLE reservation
ADD INDEX source_id (source_id);

--
-- Create foreign key
--
ALTER TABLE reservation
ADD CONSTRAINT reservation_ibfk_1 FOREIGN KEY (customer_id)
REFERENCES customer (customer_id);

--
-- Create table `reservation_table`
--
CREATE TABLE reservation_table (
  reservation_id bigint NOT NULL,
  table_id bigint NOT NULL,
  PRIMARY KEY (reservation_id, table_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create foreign key
--
ALTER TABLE reservation_table
ADD CONSTRAINT reservation_table_ibfk_1 FOREIGN KEY (reservation_id)
REFERENCES reservation (reservation_id);

--
-- Create foreign key
--
ALTER TABLE reservation_table
ADD CONSTRAINT reservation_table_ibfk_2 FOREIGN KEY (table_id)
REFERENCES restaurant_table (table_id);

--
-- Create table `orders`
--
CREATE TABLE orders (
  order_id bigint NOT NULL AUTO_INCREMENT,
  table_id bigint NOT NULL,
  staff_id bigint NOT NULL,
  source_id tinyint UNSIGNED NOT NULL COMMENT 'OrderSource (numeric enum in app)',
  order_status tinyint UNSIGNED NOT NULL DEFAULT 1 COMMENT 'OrderStatus: 1=PENDING,2=IN_PROGRESS,3=COMPLETED,4=CANCELLED',
  created_at datetime DEFAULT CURRENT_TIMESTAMP,
  customer_id bigint NOT NULL,
  updated_at datetime DEFAULT NULL,
  total_amount decimal(14, 2) NOT NULL,
  tip_amount decimal(14, 2) DEFAULT NULL,
  PRIMARY KEY (order_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create index `idx_order_status` on table `orders`
--
ALTER TABLE orders
ADD INDEX idx_order_status (created_at);

--
-- Create index `source_id` on table `orders`
--
ALTER TABLE orders
ADD INDEX source_id (source_id);

--
-- Create foreign key
--
ALTER TABLE orders
ADD CONSTRAINT FK_orders_customer_id FOREIGN KEY (customer_id)
REFERENCES customer (customer_id);

--
-- Create foreign key
--
ALTER TABLE orders
ADD CONSTRAINT orders_ibfk_1 FOREIGN KEY (table_id)
REFERENCES restaurant_table (table_id);

--
-- Create foreign key
--
ALTER TABLE orders
ADD CONSTRAINT orders_ibfk_2 FOREIGN KEY (staff_id)
REFERENCES staff_account (account_id);

--
-- Create table `payment`
--
CREATE TABLE payment (
  payment_id bigint NOT NULL AUTO_INCREMENT,
  order_id bigint NOT NULL,
  method_id tinyint UNSIGNED NOT NULL COMMENT 'PaymentMethod (numeric enum in app)',
  received_amount decimal(14, 2) NOT NULL,
  change_amount decimal(14, 2) NOT NULL,
  paid_at datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (payment_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create index `method_id` on table `payment`
--
ALTER TABLE payment
ADD INDEX method_id (method_id);

--
-- Create foreign key
--
ALTER TABLE payment
ADD CONSTRAINT payment_ibfk_1 FOREIGN KEY (order_id)
REFERENCES orders (order_id);

--
-- Create table `dish_category`
--
CREATE TABLE dish_category (
  category_id bigint NOT NULL AUTO_INCREMENT,
  category_name varchar(100) NOT NULL,
  PRIMARY KEY (category_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create table `dish`
--
CREATE TABLE dish (
  dish_id bigint NOT NULL AUTO_INCREMENT,
  category_id bigint NOT NULL,
  dish_name varchar(200) NOT NULL,
  price decimal(12, 2) NOT NULL,
  dish_status tinyint UNSIGNED NOT NULL DEFAULT 1 COMMENT 'DishStatus: 1=AVAILABLE,2=OUT_OF_STOCK,3=HIDDEN',
  created_at datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (dish_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create foreign key
--
ALTER TABLE dish
ADD CONSTRAINT dish_ibfk_1 FOREIGN KEY (category_id)
REFERENCES dish_category (category_id);

--
-- Create table `order_item`
--
CREATE TABLE order_item (
  order_item_id bigint NOT NULL AUTO_INCREMENT,
  order_id bigint NOT NULL,
  dish_id bigint NOT NULL,
  quantity int NOT NULL,
  price decimal(12, 2) NOT NULL,
  item_status tinyint UNSIGNED NOT NULL DEFAULT 1 COMMENT 'OrderItemStatus: 1=CREATED,2=IN_PROGRESS,3=READY,4=SERVED,5=REJECTED',
  reject_reason varchar(255) DEFAULT NULL,
  PRIMARY KEY (order_item_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create foreign key
--
ALTER TABLE order_item
ADD CONSTRAINT order_item_ibfk_1 FOREIGN KEY (order_id)
REFERENCES orders (order_id);

--
-- Create foreign key
--
ALTER TABLE order_item
ADD CONSTRAINT order_item_ibfk_2 FOREIGN KEY (dish_id)
REFERENCES dish (dish_id);

--
-- Create table `dish_media`
--
CREATE TABLE dish_media (
  dish_id bigint NOT NULL,
  media_id bigint NOT NULL,
  is_primary tinyint(1) DEFAULT 0,
  PRIMARY KEY (dish_id, media_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create foreign key
--
ALTER TABLE dish_media
ADD CONSTRAINT dish_media_ibfk_1 FOREIGN KEY (dish_id)
REFERENCES dish (dish_id);

--
-- Create foreign key
--
ALTER TABLE dish_media
ADD CONSTRAINT dish_media_ibfk_2 FOREIGN KEY (media_id)
REFERENCES media_asset (media_id);

--
-- Create table `supplier`
--
CREATE TABLE supplier (
  supplier_id bigint NOT NULL AUTO_INCREMENT,
  supplier_name varchar(200) NOT NULL,
  phone varchar(50) DEFAULT NULL,
  email varchar(150) DEFAULT NULL,
  PRIMARY KEY (supplier_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create table `ingredient`
--
CREATE TABLE ingredient (
  ingredient_id bigint NOT NULL AUTO_INCREMENT,
  ingredient_name varchar(200) NOT NULL,
  unit varchar(20) NOT NULL,
  supplier_id bigint DEFAULT NULL,
  PRIMARY KEY (ingredient_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create foreign key
--
ALTER TABLE ingredient
ADD CONSTRAINT FK_ingredient_supplier_id FOREIGN KEY (supplier_id)
REFERENCES supplier (supplier_id);

--
-- Create table `recipe`
--
CREATE TABLE recipe (
  dish_id bigint NOT NULL,
  ingredient_id bigint NOT NULL,
  quantity decimal(12, 3) NOT NULL,
  unit varchar(20) NOT NULL,
  note varchar(255) DEFAULT NULL,
  PRIMARY KEY (dish_id, ingredient_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create index `idx_recipe_ingredient` on table `recipe`
--
ALTER TABLE recipe
ADD INDEX idx_recipe_ingredient (ingredient_id);

--
-- Create foreign key
--
ALTER TABLE recipe
ADD CONSTRAINT fk_recipe_dish FOREIGN KEY (dish_id)
REFERENCES dish (dish_id);

--
-- Create foreign key
--
ALTER TABLE recipe
ADD CONSTRAINT fk_recipe_ingredient FOREIGN KEY (ingredient_id)
REFERENCES ingredient (ingredient_id);

--
-- Create table `inventory_transaction_item`
--
CREATE TABLE inventory_transaction_item (
  transaction_item_id bigint NOT NULL AUTO_INCREMENT,
  transaction_id bigint NOT NULL,
  ingredient_id bigint NOT NULL,
  quantity decimal(14, 3) NOT NULL,
  unit varchar(20) NOT NULL,
  note varchar(255) DEFAULT NULL,
  PRIMARY KEY (transaction_item_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create index `idx_inventory_transaction_item_ingredient` on table `inventory_transaction_item`
--
ALTER TABLE inventory_transaction_item
ADD INDEX idx_inventory_transaction_item_ingredient (ingredient_id);

--
-- Create index `idx_inventory_transaction_item_transaction` on table `inventory_transaction_item`
--
ALTER TABLE inventory_transaction_item
ADD INDEX idx_inventory_transaction_item_transaction (transaction_id);

--
-- Create index `uq_inventory_transaction_item` on table `inventory_transaction_item`
--
ALTER TABLE inventory_transaction_item
ADD UNIQUE INDEX uq_inventory_transaction_item (transaction_id, ingredient_id);

--
-- Create foreign key
--
ALTER TABLE inventory_transaction_item
ADD CONSTRAINT fk_inventory_transaction_item_ingredient FOREIGN KEY (ingredient_id)
REFERENCES ingredient (ingredient_id);

--
-- Create foreign key
--
ALTER TABLE inventory_transaction_item
ADD CONSTRAINT fk_inventory_transaction_item_transaction FOREIGN KEY (transaction_id)
REFERENCES inventory_transaction (transaction_id) ON DELETE CASCADE;

--
-- Create table `current_stock`
--
CREATE TABLE current_stock (
  ingredient_id bigint NOT NULL,
  quantity_on_hand decimal(14, 3) NOT NULL DEFAULT 0.000,
  last_updated_at datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (ingredient_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create foreign key
--
ALTER TABLE current_stock
ADD CONSTRAINT fk_current_stock_ingredient FOREIGN KEY (ingredient_id)
REFERENCES ingredient (ingredient_id);

--
-- Create table `service_error_category`
--
CREATE TABLE service_error_category (
  category_id bigint NOT NULL AUTO_INCREMENT,
  category_code varchar(50) NOT NULL,
  category_name varchar(150) NOT NULL,
  description varchar(255) DEFAULT NULL,
  PRIMARY KEY (category_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create index `category_code` on table `service_error_category`
--
ALTER TABLE service_error_category
ADD UNIQUE INDEX category_code (category_code);

--
-- Create table `service_error`
--
CREATE TABLE service_error (
  error_id bigint NOT NULL AUTO_INCREMENT,
  staff_id bigint NOT NULL,
  order_id bigint DEFAULT NULL,
  order_item_id bigint DEFAULT NULL,
  table_id bigint DEFAULT NULL,
  category_id bigint NOT NULL,
  severity_id tinyint UNSIGNED NOT NULL COMMENT 'Severity (numeric enum in app)',
  description varchar(500) NOT NULL,
  penalty_amount decimal(12, 2) DEFAULT 0.00,
  is_resolved tinyint(1) DEFAULT 0,
  resolved_by bigint DEFAULT NULL,
  resolved_at datetime DEFAULT NULL,
  created_at datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (error_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create index `idx_service_error_order` on table `service_error`
--
ALTER TABLE service_error
ADD INDEX idx_service_error_order (order_id);

--
-- Create index `idx_service_error_staff` on table `service_error`
--
ALTER TABLE service_error
ADD INDEX idx_service_error_staff (staff_id, created_at);

--
-- Create index `severity_id` on table `service_error`
--
ALTER TABLE service_error
ADD INDEX severity_id (severity_id);

--
-- Create foreign key
--
ALTER TABLE service_error
ADD CONSTRAINT service_error_ibfk_1 FOREIGN KEY (staff_id)
REFERENCES staff_account (account_id);

--
-- Create foreign key
--
ALTER TABLE service_error
ADD CONSTRAINT service_error_ibfk_2 FOREIGN KEY (order_id)
REFERENCES orders (order_id);

--
-- Create foreign key
--
ALTER TABLE service_error
ADD CONSTRAINT service_error_ibfk_3 FOREIGN KEY (order_item_id)
REFERENCES order_item (order_item_id);

--
-- Create foreign key
--
ALTER TABLE service_error
ADD CONSTRAINT service_error_ibfk_4 FOREIGN KEY (table_id)
REFERENCES restaurant_table (table_id);

--
-- Create foreign key
--
ALTER TABLE service_error
ADD CONSTRAINT service_error_ibfk_5 FOREIGN KEY (category_id)
REFERENCES service_error_category (category_id);

--
-- Create foreign key
--
ALTER TABLE service_error
ADD CONSTRAINT service_error_ibfk_7 FOREIGN KEY (resolved_by)
REFERENCES staff_account (account_id);

--
-- Create table `permission`
--
CREATE TABLE permission (
  permission_id bigint NOT NULL AUTO_INCREMENT,
  screen_code varchar(100) NOT NULL,
  action_code varchar(20) NOT NULL,
  PRIMARY KEY (permission_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 5,
AVG_ROW_LENGTH = 4096,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create table `role_permission`
--
CREATE TABLE role_permission (
  role_id bigint NOT NULL,
  permission_id bigint NOT NULL,
  PRIMARY KEY (role_id, permission_id)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 4096,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create foreign key
--
ALTER TABLE role_permission
ADD CONSTRAINT role_permission_ibfk_1 FOREIGN KEY (role_id)
REFERENCES role (role_id);

--
-- Create foreign key
--
ALTER TABLE role_permission
ADD CONSTRAINT role_permission_ibfk_2 FOREIGN KEY (permission_id)
REFERENCES permission (permission_id);

--
-- Create table `promotion`
--
CREATE TABLE promotion (
  promotion_id bigint NOT NULL AUTO_INCREMENT,
  promo_code varchar(50) DEFAULT NULL,
  promo_name varchar(200) NOT NULL,
  description varchar(255) DEFAULT NULL,
  type_id tinyint UNSIGNED NOT NULL COMMENT 'PromotionType (numeric enum in app)',
  start_time datetime NOT NULL,
  end_time datetime NOT NULL,
  promotion_status tinyint UNSIGNED NOT NULL DEFAULT 1 COMMENT 'PromotionStatus: 1=SCHEDULED,2=ACTIVE,3=EXPIRED,4=DISABLED',
  max_usage int DEFAULT NULL,
  used_count int DEFAULT 0,
  created_at datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (promotion_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create index `promo_code` on table `promotion`
--
ALTER TABLE promotion
ADD UNIQUE INDEX promo_code (promo_code);

--
-- Create index `type_id` on table `promotion`
--
ALTER TABLE promotion
ADD INDEX type_id (type_id);

--
-- Create table `promotion_target`
--
CREATE TABLE promotion_target (
  target_id bigint NOT NULL AUTO_INCREMENT,
  promotion_id bigint NOT NULL,
  dish_id bigint DEFAULT NULL,
  category_id bigint DEFAULT NULL,
  PRIMARY KEY (target_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create foreign key
--
ALTER TABLE promotion_target
ADD CONSTRAINT promotion_target_ibfk_1 FOREIGN KEY (promotion_id)
REFERENCES promotion (promotion_id);

--
-- Create foreign key
--
ALTER TABLE promotion_target
ADD CONSTRAINT promotion_target_ibfk_2 FOREIGN KEY (dish_id)
REFERENCES dish (dish_id);

--
-- Create foreign key
--
ALTER TABLE promotion_target
ADD CONSTRAINT promotion_target_ibfk_3 FOREIGN KEY (category_id)
REFERENCES dish_category (category_id);

--
-- Create table `promotion_rule`
--
CREATE TABLE promotion_rule (
  rule_id bigint NOT NULL AUTO_INCREMENT,
  promotion_id bigint NOT NULL,
  min_order_value decimal(14, 2) DEFAULT NULL,
  min_quantity int DEFAULT NULL,
  required_dish_id bigint DEFAULT NULL,
  required_category_id bigint DEFAULT NULL,
  PRIMARY KEY (rule_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create foreign key
--
ALTER TABLE promotion_rule
ADD CONSTRAINT promotion_rule_ibfk_1 FOREIGN KEY (promotion_id)
REFERENCES promotion (promotion_id);

--
-- Create foreign key
--
ALTER TABLE promotion_rule
ADD CONSTRAINT promotion_rule_ibfk_2 FOREIGN KEY (required_dish_id)
REFERENCES dish (dish_id);

--
-- Create foreign key
--
ALTER TABLE promotion_rule
ADD CONSTRAINT promotion_rule_ibfk_3 FOREIGN KEY (required_category_id)
REFERENCES dish_category (category_id);

--
-- Create table `order_promotion`
--
CREATE TABLE order_promotion (
  order_promotion_id bigint NOT NULL AUTO_INCREMENT,
  order_id bigint NOT NULL,
  promotion_id bigint NOT NULL,
  discount_amount decimal(14, 2) NOT NULL,
  applied_at datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (order_promotion_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create index `idx_invoice_promo_promo` on table `order_promotion`
--
ALTER TABLE order_promotion
ADD INDEX idx_invoice_promo_promo (promotion_id);

--
-- Create index `uq_invoice_promo` on table `order_promotion`
--
ALTER TABLE order_promotion
ADD UNIQUE INDEX uq_invoice_promo (order_id, promotion_id);

--
-- Create foreign key
--
ALTER TABLE order_promotion
ADD CONSTRAINT FK_invoice_promotion_order_id FOREIGN KEY (order_id)
REFERENCES orders (order_id);

--
-- Create foreign key
--
ALTER TABLE order_promotion
ADD CONSTRAINT order_promotion_ibfk_2 FOREIGN KEY (promotion_id)
REFERENCES promotion (promotion_id);

-- 
-- Dumping data for table role
--
INSERT INTO role(role_id, role_code, role_name) VALUES
(1, 'ADMIN', 'Admin'),
(2, 'STAFF', 'Staff');

-- Table restaurant_mgmt.media_asset does not contain any data (it is empty)

-- 
-- Dumping data for table staff_account
--
INSERT INTO staff_account(account_id, full_name, phone, email, role_id, account_status, created_at, username, password_hash, is_locked, last_login_at) VALUES
(1, 'dat', '0342164017', 'nguyenducdat0406@gmail.com', 2, 1, '2026-01-22 23:16:23', 'staff_test_acc', '$2a$12$rhk/zM/TqwgdrIcbpJ4ht.RqTSCcECuk7cVTDElt8ZiRktP7rOKe.', 0, '2026-01-26 16:05:59'),
(2, 'admin', '0999999999', 'admin@gmail.com', 1, 1, '2026-01-22 23:19:05', 'admin', '$2a$12$PGj7asKjGxknX3QWEO9YV.sR/jI4gDXgv2e/NSz/yhY6fmfsZoi4q', 0, '2026-01-22 16:32:57');

-- Table restaurant_mgmt.restaurant_table does not contain any data (it is empty)

-- Table restaurant_mgmt.customer does not contain any data (it is empty)

-- Table restaurant_mgmt.dish_category does not contain any data (it is empty)

-- Table restaurant_mgmt.orders does not contain any data (it is empty)

-- Table restaurant_mgmt.dish does not contain any data (it is empty)

-- Table restaurant_mgmt.supplier does not contain any data (it is empty)

-- Table restaurant_mgmt.service_error_category does not contain any data (it is empty)

-- Table restaurant_mgmt.order_item does not contain any data (it is empty)

-- 
-- Dumping data for table permission
--
INSERT INTO permission(permission_id, screen_code, action_code) VALUES
(1, 'ACCOUNT', 'CREATE'),
(2, 'ACCOUNT', 'UPDATE'),
(3, 'ACCOUNT', 'DELETE'),
(4, 'ACCOUNT', 'READ');

-- Table restaurant_mgmt.reservation does not contain any data (it is empty)

-- Table restaurant_mgmt.promotion does not contain any data (it is empty)

-- Table restaurant_mgmt.inventory_transaction does not contain any data (it is empty)

-- Table restaurant_mgmt.ingredient does not contain any data (it is empty)

-- Table restaurant_mgmt.table_media does not contain any data (it is empty)

-- Table restaurant_mgmt.service_error does not contain any data (it is empty)

-- 
-- Dumping data for table role_permission
--
INSERT INTO role_permission(role_id, permission_id) VALUES
(1, 1),
(1, 2),
(1, 3),
(1, 4);

-- Table restaurant_mgmt.reservation_table does not contain any data (it is empty)

-- Table restaurant_mgmt.recipe does not contain any data (it is empty)

-- Table restaurant_mgmt.promotion_target does not contain any data (it is empty)

-- Table restaurant_mgmt.promotion_rule does not contain any data (it is empty)

-- Table restaurant_mgmt.payment does not contain any data (it is empty)

-- Table restaurant_mgmt.order_promotion does not contain any data (it is empty)

-- Table restaurant_mgmt.inventory_transaction_media does not contain any data (it is empty)

-- Table restaurant_mgmt.inventory_transaction_item does not contain any data (it is empty)

-- Table restaurant_mgmt.dish_media does not contain any data (it is empty)

-- Table restaurant_mgmt.current_stock does not contain any data (it is empty)

-- 
-- Dumping data for table auth_session
--
INSERT INTO auth_session(session_id, user_id, token_hash, expires_at, created_at, revoked, device_info, ip_address) VALUES
(1, 2, '+4ZiJILZ0OEypxAyrrNok8zXdsnSutADmosGItP4gLo=', '2026-01-29 16:32:18', '2026-01-22 16:32:19', 0, 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/144.0.0.0 Safari/537.36', '::1'),
(2, 1, 'g0dFYb4s8ZMy2BmvygINHw6Ev3gciUz/E5DrS1i1OCQ=', '2026-02-02 16:05:59', '2026-01-26 16:05:59', 0, 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/144.0.0.0 Safari/537.36', '::1');

-- Table restaurant_mgmt.audit_log does not contain any data (it is empty)

--
-- Restore previous SQL mode
--
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

--
-- Enable foreign keys
--
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;